name: ESLint Check
on: [push]
jobs:
  Run-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
      - uses: actions/checkout@v3
      - name: Install Dependencies
      - uses: yarn install
      - run: echo "Run ESLint"
      - run: yarn run lint
      - run: echo "ğŸ This job's status is ${{ job.status }}."
